steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '-f', 'backend/Dockerfile', 'backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image=${_IMAGE}'
      - '--region=${_REGION}'
      - '--platform=managed'

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: 'northamerica-northeast1-docker.pkg.dev/foodie-503510/cloud-run-source-deploy/schoolio:${SHORT_SHA}'
  _SERVICE_NAME: 'schoolio'
  _REGION: 'northamerica-northeast1'
